# -*- coding: utf-8 -*-
"""Hypothesis_Testing

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hv0ZwThzh02y85y5UYA7xtF4O2iHTiML

**Hypothesis Testing:** 

Hypothesis testing or significance testing is a method for testing a claim or
hypothesis about a parameter in a population, using data measured in a
sample. In this method, we test some hypothesis by determining the
likelihood that a sample statistic could have been selected, if the hypothesis
regarding the population parameter were true.

(Introduction to Hypothesis Testing Chapter8 - https://www.sagepub.com/sites/default/files/upm-binaries/40007_Chapter8.pdf )

The general idea of hypothesis testing involves:

1- Making an initial assumption.

2- Collecting evidence (data).

3- Based on the available evidence (data), deciding whether to reject or not reject the initial assumption.

Every hypothesis test — regardless of the population parameter involved — requires the above three steps.

(PennState Statistics Online S.3 Hypothesis Testing - https://online.stat.psu.edu/statprogram/reviews/statistical-concepts/hypothesis-testing )

p-value <= alpha, then Null Hypothesis is rejected. Alpha value is generally 0.05.

1 - Alpha = Confidence level

1 - Beta is power of the test, if has to be generally >= 0.8

**One-Sample T-test:**

A one sample test of means compares the mean of a sample to a pre-specified value and tests for a deviation from that value.

The assumptions of the one-sample t-test are:
1. The data are continuous (not discrete).
2. The data follow the normal probability distribution.
3. The sample is a simple random sample from its population. Each individual in the population has an equal
probability of being selected in the sample.

Assume that average salary of 5 years experienced person in India is Rs 60,000 per month

H0: Average Salary = 60000

Ha: Average Salary is not equal to 60000
"""

import numpy as np
import pandas as pd

Salary = np.array([57000, 30000, 59000, 65000, 84000, 53000, 35000, 90000, 44000, 82000, 67000, 64000, 58000, 53000, 41000, 39000, 80000, 87000, 73000, 65000, 28000, 62000, 67000, 47000, 36000, 72000, 89000, 67000, 89000, 90000])

"""The len() Python method returns the length of a list, string, dictionary, or any other iterable data format in Python."""

len(Salary)

Salary.mean()

"""**t-test:**

Sample Size less than 30 or Standard Deviation of Population is not known 
"""

import scipy.stats as stats

stats.ttest_1samp(a=Salary, popmean=60000)

"""p-value is greater than 0.05, failed to reject null hypothesis.

Above is the two tailed t-test.

If H0 is Salary of 5 years experience employee is greater than or equal to Rs 60000 in India - One tailed t-test. 

p-value of one tailed t-test = p-value of two tailed t-test / 2

**Power Analysis:** 

Statistical power is the probability that the given experiment correctly rejecets the null hypothesis when the alternative hypothesis is true.

Power Analysis is used to calculate the sample size required.

An effect size is a way to quantify the difference between two groups. 

Statistical Significance is represented by p-value, practical significance is represented by effect size.
"""

from statsmodels.stats.power import TTestIndPower
effect_size = 0.5
alpha = 0.05
power = 0.8
p_analysis = TTestIndPower()
p_analysis.solve_power(effect_size=effect_size, alpha=alpha, power=power)

"""While statistical significance shows that an effect exists in a study, practical significance shows that the effect is large enough to be meaningful in the real world.

Statistical significance alone can be misleading because it’s influenced by the sample size. Increasing the sample size always makes it more likely to find a statistically significant effect, no matter how small the effect truly is in the real world.

In contrast, effect sizes are independent of the sample size. Only the data is used to calculate effect sizes.

https://www.scribbr.com/statistics/effect-size/
"""