# -*- coding: utf-8 -*-
"""Two-sample_t-test

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QHlEJn08pTOSpIgJuCVghUObrwks4SNN

**Two Sample t-Test:**

Two samples from two independent population, also known as unpaired t-test.

Assume that average salary of 5 years experienced person in IT sector and Automobile sector are not equal. 

H0: Salary of IT Sector = Salary of Automobile sector

Ha: Salary of IT Sector =! Salary of Automobile sector
"""

import pandas as pd
import numpy as np

IT = np.array([56000, 95000, 99000, 65000, 84000, 64000, 139000, 90000, 44000, 82000, 67000, 64000, 58000, 53000, 41000, 69000, 81000, 87000, 73000, 65000, 90000, 62000, 72000, 76000, 54000, 56000, 45000, 72000, 62000, 92000])
Auto = np.array([53000, 45000, 69000, 65000, 74000, 66000, 89000, 90000, 44000, 62000, 60000, 64000, 58000, 70000, 55000, 69000, 80000, 67000, 90000, 70000, 78000, 62000, 54000, 50000, 79000, 55000, 49000, 70000, 55000, 62000])

len(IT)

len(Auto)

IT.mean()

Auto.mean()

import scipy.stats as stats
stats.ttest_ind(Auto, IT)

"""p-value = 0.123 which is greater than 0.05 hence Null Hypothesis cannot be rejected. i.e. we don't have sufficient evidence to prove that average salary of 5 years experience in IT sector and Automobile sector is not equal.

Note:

A p-value higher than 0.05 (> 0.05) is not statistically significant and indicates strong evidence for the null hypothesis. This means we retain the null hypothesis and reject the alternative hypothesis. You should note that you cannot accept the null hypothesis, we can only reject the null or fail to reject it.

https://www.simplypsychology.org/p-value.html#:~:text=A%20p%2Dvalue%20higher%20than,or%20fail%20to%20reject%20it.

**Paired t-test:**

Two samples taken from population and measured at two different time intervals.

Average Salary of 5 years experienced professional before COVID-19 first wave is greater than after COVID-19 first wave

H0: Salary before firstwave <= Salary after first wave

Ha: Salary before firstwave > Salary after first wave
"""

Before = np.array([67000, 55000, 54000, 95000, 84000, 96000, 89000, 90000, 49000, 82000, 80000, 84000, 58000, 53000, 41000, 69000, 80000, 87000, 73000, 65000, 68000, 62000, 70000, 82000, 56000, 54000, 80000, 67000, 75000, 72000])
After = np.array([57000, 45000, 49000, 65000, 74000, 66000, 59000, 90000, 48000, 62000, 67000, 64000, 58000, 65000, 55000, 69000, 80000, 67000, 70000, 65000, 79000, 62000, 53000, 72000, 67000, 68000, 72000, 52000, 55000, 65000])

Before.mean()

After.mean()

"""**scipy.stats.ttest_rel**(a, b, axis=0, nan_policy='propagate', alternative='two-sided')
Calculate the t-test on TWO RELATED samples of scores, a and b.

This is a two-sided test for the null hypothesis that 2 related or repeated samples have identical average (expected) values.

https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ttest_rel.html
"""

stats.ttest_rel(Before, After)

"""p-value = 0.0043 is less than 0.05 hence null hypothesis is rejected in support of alternate hypothesis."""